{
 "title": "Mainnet V1 Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Expired feeds count",
   "type": "stat",
   "description": "The number of expired feeds (all the price points have expired)",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "expired_feeds_count{network=\"mainnet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ADA Price in USD",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "ADA_price{network=\"mainnet\"}",
     "legendFormat": "ada_price"
    }
   ]
  },
  {
   "title": "Datums Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "datums_count{network=\"mainnet\"}",
     "legendFormat": "datums_count"
    },
    {
     "expr": "valid_datums_count{network=\"mainnet\"}",
     "legendFormat": "valid_datums_count"
    },
    {
     "expr": "expired_datums_count{network=\"mainnet\"}",
     "legendFormat": "expired_datums_count"
    }
   ]
  },
  {
   "title": "FACT Price in ADA",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "FACT_price{network=\"mainnet\"}",
     "legendFormat": "ada_price"
    }
   ]
  },
  {
   "title": "UTxO Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "utxo_count{network=\"mainnet\"}",
     "legendFormat": "utxo_count"
    }
   ]
  },
  {
   "title": "Arweave Wallet Balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "arweave_wallet_balance{network=\"mainnet\"}",
     "legendFormat": "arweave_wallet_balance (winstons)"
    }
   ]
  },
  {
   "title": "Wallets Amounts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "submitter_addr_amount{network=\"mainnet\"} / 1000000",
     "legendFormat": "submitter_wallet_amount"
    },
    {
     "expr": "smart_contract_amount{network=\"mainnet\"} / 1000000",
     "legendFormat": "smart_contract_amount"
    },
    {
     "expr": "fee_addr_amount{network=\"mainnet\"} / 1000000",
     "legendFormat": "fee_addr_amount"
    }
   ]
  },
  {
   "title": "Arweave transactions left",
   "type": "timeseries",
   "description": "How many transactions can be done with the existing wallet funds",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "arweave_txs_funds{network=\"mainnet\"}",
     "legendFormat": "arweave_txs_funds"
    }
   ]
  }
 ]
}