{
 "title": "Archivematica (Localhost)",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "AIPs and SIPs over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(createdTime) as time,\n  count(sipUUID) as \"all SIPs and AIPs\"\nFROM SIPs\nGROUP BY substr(createdTime,1,7)"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(createdTime) as time,\n  count(sipUUID) as \"stored AIPs\"\nFROM SIPs\nwhere aipFilename is not null\nGROUP BY substr(createdTime,1,7)"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(createdTime) as time,\n  count(sipUUID) as \"rejected AIPs\"\nFROM SIPs\nwhere currentPath like \"%rejected%\"\nGROUP BY substr(createdTime,1,7)"
    }
   ]
  },
  {
   "title": "Formats in Archivematica",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n   FilesIDs.formatRegistryKey,\n   FilesIDs.formatName as \"formatname\",\n   FilesIDs.formatVersion as \"formatversion\",\n   count(*) as count\nfrom Files\ninner join FilesIDs\nwhere fileGrpUse = 'original'\nand Files.fileUUID = FilesIDs.fileUUID\ngroup by FilesIDs.formatRegistryKey\norder by count desc"
    }
   ]
  },
  {
   "title": "Storage Service AIP sizes and statuses",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select\n\tUUID as \"AIP uuid\",\n\tsize, \n    status\nfrom locations_package\nwhere package_type = \"AIP\"\norder by size desc"
    }
   ]
  },
  {
   "title": "Oldest file timestamp in Archivematica",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \n\tmodificationTime\nfrom Files\nwhere fileGrpUse = \"original\"\norder by modificationTime asc\nlimit 1"
    }
   ]
  },
  {
   "title": "Date range of files in Archivematica",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "select \n\tmodificationTime as Date,\n  SUBSTRING_INDEX(originalLocation, '/', -1) as Filename\nfrom Files\nwhere fileGrpUse = 'original'\norder by modificationTime asc"
    }
   ]
  },
  {
   "title": "Latest longest running task in AM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \n\tCONCAT(TasksConfigs.description, ': ', timeDiff(Tasks.endTime, Tasks.startTime))\nfrom Tasks\ninner join TasksConfigs\ninner join StandardTasksConfigs\nwhere TasksConfigs.taskTypePKReference = StandardTasksConfigs.pk\nand StandardTasksConfigs.execute = Tasks.exec\norder by timeDiff(Tasks.endTime, Tasks.startTime) desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Latest shortest running task in AM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \n\tCONCAT(TasksConfigs.description, ': ', timeDiff(Tasks.endTime, Tasks.startTime))\nfrom Tasks\ninner join TasksConfigs\ninner join StandardTasksConfigs\nwhere TasksConfigs.taskTypePKReference = StandardTasksConfigs.pk\nand StandardTasksConfigs.execute = Tasks.exec\norder by timeDiff(Tasks.endTime, Tasks.startTime) asc\nlimit 1"
    }
   ]
  },
  {
   "title": "AIP Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "?",
     "rawSql": "select count(*) from SIPs where aipFilename is not NULL\n",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Preservation Metadata",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 19 },
   "targets": [
    {
     "rawSql": "select count(*) as 'Preservation Masters' from Files where fileGrpuse = 'original'"
    },
    {
     "rawSql": "select count(*) as 'Access Derivatives' from Files where fileGrpuse = 'access'"
    }
   ]
  },
  {
   "title": "Newest file timestamp in Archivematica",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \n\tmodificationTime\nfrom Files\nwhere fileGrpUse = \"original\"\norder by modificationTime desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Failed and rejected AIPs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from SIPs\nwhere aipFilename is null\nand currentPath like \"%failed%\" \nor currentPath like \"%rejected%\""
    }
   ]
  },
  {
   "title": "AIPs Processing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "?",
     "rawSql": "select count(*) from SIPs\nwhere aipFilename is null\nand currentPath not like \"%failed%\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Dashboard UUID",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select value as \"Dashboard UUID\"\nfrom DashboardSettings\nwhere name = \"dashboard_uuid\""
    }
   ]
  }
 ]
}